apiVersion: "v1"
kind: "PersistentVolumeClaim"
metadata:
  name: redis-volume-claim
  namespace: default
spec:
  storageClassName: local-path
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
  volumeName: redis-volume
